/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasePagination: typeof import('./src/components/base/BasePagination.vue')['default']
    BaseSearchForm: typeof import('./src/components/base/BaseSearchForm.vue')['default']
    BaseTableContainer: typeof import('./src/components/base/BaseTableContainer.vue')['default']
    CategoryDialog: typeof import('./src/components/process/CategoryDialog.vue')['default']
    DepartmentDialog: typeof import('./src/components/department/DepartmentDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconChannel: typeof import('./src/components/icons/IconChannel.vue')['default']
    IconCode: typeof import('./src/components/icons/IconCode.vue')['default']
    IconConfig: typeof import('./src/components/icons/IconConfig.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconModel: typeof import('./src/components/icons/IconModel.vue')['default']
    IconNotFound: typeof import('./src/components/icons/IconNotFound.vue')['default']
    IconOrder: typeof import('./src/components/icons/IconOrder.vue')['default']
    IconProduct: typeof import('./src/components/icons/IconProduct.vue')['default']
    IconStatistics: typeof import('./src/components/icons/IconStatistics.vue')['default']
    IconTask: typeof import('./src/components/icons/IconTask.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    IconWelcome: typeof import('./src/components/icons/IconWelcome.vue')['default']
    ProcessDialog: typeof import('./src/components/task/ProcessDialog.vue')['default']
    ProcessTable: typeof import('./src/components/task/ProcessTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StandardProcessDialog: typeof import('./src/components/process/StandardProcessDialog.vue')['default']
    SubTaskDialog: typeof import('./src/components/task/SubTaskDialog.vue')['default']
    TaskDialog: typeof import('./src/components/task/TaskDialog.vue')['default']
    UserDialog: typeof import('./src/components/user/UserDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
