/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasePagination: typeof import('./src/components/base/BasePagination.vue')['default']
    BaseSearchForm: typeof import('./src/components/base/BaseSearchForm.vue')['default']
    BaseTableContainer: typeof import('./src/components/base/BaseTableContainer.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IconChannel: typeof import('./src/components/icons/IconChannel.vue')['default']
    IconCode: typeof import('./src/components/icons/IconCode.vue')['default']
    IconConfig: typeof import('./src/components/icons/IconConfig.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconModel: typeof import('./src/components/icons/IconModel.vue')['default']
    IconNotFound: typeof import('./src/components/icons/IconNotFound.vue')['default']
    IconOrder: typeof import('./src/components/icons/IconOrder.vue')['default']
    IconProduct: typeof import('./src/components/icons/IconProduct.vue')['default']
    IconStatistics: typeof import('./src/components/icons/IconStatistics.vue')['default']
    IconTask: typeof import('./src/components/icons/IconTask.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
